### ISSUE TITLE
yolov3-tiny training error

### ISSUE THREAD

**Issue by andylai0212** [talebolano/yolov3-network-slimming#12]
你好，在訓練yolov3-tiny報錯:
load network
done!
load weightsfile
done!
/home/andy0212/anaconda3/lib/python3.7/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
/home/andy0212/anaconda3/lib/python3.7/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
/home/andy0212/anaconda3/lib/python3.7/site-packages/torch/nn/_reduction.py:16: UserWarning: reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.
  warnings.warn("reduction='elementwise_mean' is deprecated, please use reduction='mean' instead.")
/home/andy0212/anaconda3/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "sparsity_train.py", line 154, in <module>
    train()
  File "sparsity_train.py", line 100, in train
    loss = model(imgs, targets)
  File "/home/andy0212/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/andy0212/Documents/yolov3-network-slimming/yolomodel.py", line 332, in forward
    x = torch.cat((map1, map2), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 26 and 24 in dimension 2 at /opt/conda/conda-bld/pytorch_1549635019666/work/aten/src/THC/generic/THCTensorMath.cu:83

**Comment by AntoineGerardeaux** [comment]
Same error, we need a fix

**Comment by cococener** [comment]
请问你现在问题解决了吗？我遇到了一个类似的问题？

**Comment by AbanoubMamdouh** [comment]
@talebolano I have the same problem, is the code working correctly on yolov3 tiny architecture?

**Comment by JadeQuinn** [comment]
same error,have you fixed it?

**Comment by smallworld-network-wupeng** [comment]
me too
