### ISSUE TITLE
我训练自己的数据集在微调的时候碰到这种错误

### ISSUE THREAD

**Issue by lizhaokun** [talebolano/yolov3-network-slimming#24]
Traceback (most recent call last):
  File "sparsity_train.py", line 161, in <module>
    train()
  File "sparsity_train.py", line 66, in train
    model.load_weights(args.weightsfile)
  File "/home/lizhaokun/code/yolo/yolov3-network-slimming-master/yolomodel.py", line 427, in load_weights
    conv_weights = conv_weights.view_as(conv.weight.data)
RuntimeError: shape '[1024, 512, 3, 3]' is invalid for input of size 2024224
我的类别是2类，cfg的类别和yolo层上面那一层的filter个数我都改过了，有人知道是为什么吗？

**Comment by thorstenbar** [comment]
Did you find a solution? I am running into the same problem, when trying to use the pruned weights.
